version: "3"

tasks:
  update:
    desc: Updates all dependencies
    aliases: [up]
    silent: true
    cmds:
      - go mod tidy

  build:
    desc: Build a local snapshot with goreleaser
    silent: true
    cmds:
      - "goreleaser release --snapshot --clean --skip=publish"

  generate:
    aliases: [gen]
    silent: true
    cmd: go generate ./...

  lint:
    desc: Run golangci-lint on the codebase
    silent: true
    cmd: "golangci-lint run {{.CLI_ARGS}}"

  lint:fix:
    desc: Run golangci-lint --fix on the codebase
    silent: true
    cmds:
      - go fix ./...
      - golangci-lint run --fix

  test:
    desc: Run the test suite (unit tests only)
    silent: true
    cmd: go test ./... -cover -short

  test:ci:
    desc: Run the test suite for CI with coverage profile
    silent: true
    cmd: go test -v -coverprofile=coverage.out ./...
